config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :artists
  resources :playlists
  resources :tracks
  resources :albums
  resources :styles
  resource :admins
  resource :selections
  resource :display_favorite_artists
  resource :display_favorite_albums
  resources :favorite_artists, only: [:create, :destroy]
  resources :favorite_albums, only: [:create, :destroy]
  root 'index#index'
  get 'index' => 'home#index'
  get 'favorite_artists' => 'display_favorite_artists#show'
  get 'favorite_albums' => 'display_favorite_albums#show'

  resources :artists do
     member do
        put "like" => "artists#upvote"
        put "dislike" => "artists#downvote"
     end
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base

   extend FriendlyId

   include SearchCop

   acts_as_votable

   has_many :albums

   has_attached_file :avatar, styles: {
      medium: '200x200',
      thumb: '100x100'
   }

   validates_attachment_content_type :avatar, content_type: /\Aimage/
   validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/, /gif\Z/]
   validates_with AttachmentSizeValidator,
      attributes: :avatar,
      less_than: 5.megabytes
   do_not_validate_attachment_file_type :avatar

   search_scope :search do
      attributes :name, :slug
   end

   friendly_id :slug_candidates, use: [:slugged, :finders]

   def slug_candidates
      [ :name, [:id, :name] ]
   end

   def should_generate_new_friendly_id?
      name_changed? || super
   end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
   authorize_resource
   before_action :set_artist, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
   before_action :display_playlists

   def index
      @artists = Artist.all

      if params[:artists]
         @search_value = search_params[:search]
         @artists = @artists.search(@search_value)
      end
   end

   def show
   end

   def new
     @artist = Artist.new
  end

  def edit
  end

  def create
      @artist = Artist.new(artist_params)

      if @artist.save
        redirect_to @artist, notice: 'Artist was successfully created.'
      else
        render :new
      end
  end

  def update
      if @artist.update(artist_params)
        redirect_to @artist, notice: 'Artist was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @artist.destroy
    redirect_to artists_url, notice: 'Artist was successfully destroyed.'
  end

  # Acts As Votable methods
  # upvote_from user
  def upvote
     @artist.upvote_from current_user
     redirect_to @artist
  end

  # downvote_from user
  def downvote
     @artist.downvote_from current_user
     redirect_to @artist
  end

  private
    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name, :firstname, :avatar, :description, album_ids: [], user_ids: [])
    end

    def search_params
      params.require(:artists).permit(:search)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= simple_form_for @artist do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
     <div class="add-field col-md-5">
        <%= f.input :name, label: 'Nom de l\'artiste' %>
     </div>
  </div>

  <div class="row">
     <div class="add-field col-md-5">
       <%= f.input :description, as: :text, label: 'Description', class: 'artist-description' %>
     </div>
  </div>

  <div class="row">
     <div class="col-md-5">
       <%= f.input :avatar, as: :file, class: 'artist-avatar' %>
     </div>
  </div>

  <div class="actions">
    <%= f.submit 'Enregistrer', class: 'btn-submit' %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<div class="back-button col-md-2">
   <i class="fa fa-arrow-left" aria-hidden="true"></i>
   <%= link_to 'Retour', artists_path %>
</div>

<div class="update-section col-md-10 col-md-offset-1">
   <h1>Modifier un artiste</h1>
   <%= render 'form' %>
</div>

app/views/artists/index.html.erb
<% if can? :create, Artist %>
   <div class="col-md-2">
      <%= link_to 'Ajouter un artiste', new_artist_path, class: 'add-new-artist add' %>
   </div>
<% end %>

<section id="search-artists" class="search-bar col-md-12">
   <%= simple_form_for :artists, url: artists_path, method: :get, html: { class: 'form-inline' } do |f| %>
      <%= f.input_field :search, label: false,
                                 placeholder: 'Rechercher un artiste',
                                 class: 'form-control',
                                 value: @search_value %>
   <% end %>
</section>

<div id="artists-list">
   <% @artists.each do |artist| %>
      <div class="artist col-md-3">
         <%= link_to artist.avatar.exists? ? image_tag(artist.avatar.url(:medium)) : '&empty;'.html_safe, artist %>
         <div class="artist-informations">
            <p class="artist-name"><%= link_to artist.name, artist %></p>
            <p class="count"><%= artist.albums.count() %> <% if artist.albums.count() > 1 %>albums<% else %> album<% end %></p>
         </div>
         <% if can? :create, Artist %>
            <div class="edit-section">
               <%= link_to 'Voir', artist %>
               <%= link_to 'Modifier', edit_artist_path(artist) %>
               <%= link_to 'Supprimer', artist, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
         <% end %>
      </div>
   <% end %>
</div>

app/views/artists/new.html.erb
<div class="back-button col-md-2">
   <i class="fa fa-arrow-left" aria-hidden="true"></i>
   <%= link_to 'Retour', artists_path %>
</div>

<div class="add-section col-md-10 col-md-offset-1">
   <h1>Ajouter un artiste</h1>
   <%= render 'form' %>
</div>

app/views/artists/show.html.erb
<div class="back-button col-md-2">
   <i class="fa fa-arrow-left" aria-hidden="true"></i>
   <%= link_to 'Retour', artists_path %>
</div>

<div class="single-artist-page col-md-11">
   <% if @artist.avatar.exists? %>
      <div class="artist-avatar col-md-4"><%= image_tag(@artist.avatar.url(:medium)) %></div>
   <% end %>

   <div class="artist-informations col-md-6">
      <h2 class="artist-name"><%= @artist.name %></h2>

      <div class="add-to-favorite">
         <%- unless current_user.favorite_artists.exists?(id: @artist.id) -%>
            <%= link_to 'S\'abonner', favorite_artists_path(artist_id: @artist), method: :post, class: 'add-to-favorite favorite-button' %>
         <%- else -%>
            <%= link_to 'Se désabonner', favorite_artist_path(@artist), method: :delete, class: 'remove-from-favorite favorite-button' %>
         <%- end -%>
      </div>

      <div class="artist-description">
         <p><%= @artist.description %></p>
      </div>

      <div id="votable-buttons">
         <%= link_to like_artist_path(@artist), class: 'like', method: :put do %>
            <button type="button" class="btn btn-info" aria-label="Left Align">
               <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
               <span class="badge"><%= @artist.get_upvotes.size %></span>
            </button>
         <% end %>

         <%= link_to dislike_artist_path(@artist), class: 'like', method: :put do %>
            <button type="button" class="btn btn-info" aria-label="Left Align">
               <span class="glyphicon glyphicon-thumbs-down glyphicon-align-center" aria-hidden="true"></span>
               <span class="badge"><%= @artist.get_downvotes.size %></span>
            </button>
         <% end %>
      </div>
   </div>

   <div id="discography" class="col-md-12">
      <div class="col-md-12">
         <h3>Discographie</h3>
      </div>
      <%# Get all the artist's albums %>
      <% @artist.albums.each do |album| %>
         <div class="album col-md-4">
            <%= link_to image_tag(album.avatar(:medium)), album %>
            <p><%= link_to album.name, album %></p>
         </div>
      <% end %>
   </div>


</div>