config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :artists
  resources :playlists
  resources :tracks
  resources :albums
  resources :styles
  resource :admins
  resource :selections
  resource :display_favorite_artists
  resource :display_favorite_albums
  resources :favorite_artists, only: [:create, :destroy]
  resources :favorite_albums, only: [:create, :destroy]
  root 'index#index'
  get 'index' => 'home#index'
  get 'favorite_artists' => 'display_favorite_artists#show'
  get 'favorite_albums' => 'display_favorite_albums#show'

  resources :artists do
     member do
        put "like" => "artists#upvote"
        put "dislike" => "artists#downvote"
     end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
     user ||= User.new

      if user.has_role?(:admin)
         can :manage, Artist
         can :manage, Playlist
         can :manage, Track
         can :manage, Album
         can :manage, Style
         can :manage, Selection
      else
         can :read, Artist
         can :read, Playlist
         can :read, Track
         can :read, Album
         can :read, Style
         can :read, Selection
      end
   end
end

app/models/album.rb
class Album < ActiveRecord::Base

   extend FriendlyId

   include SearchCop

   has_many :tracks
   belongs_to :style
   belongs_to :artist

   has_attached_file :avatar, styles: { medium: '300x300', thumb: '150x150' }

   validates_attachment_content_type :avatar, content_type: /\Aimage/
   validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/, /gif\Z/]
   validates_with AttachmentSizeValidator,
      attributes: :avatar,
      less_than: 5.megabytes
   do_not_validate_attachment_file_type :avatar

   search_scope :search do
      attributes :name, :slug
   end

   friendly_id :slug_candidates, use: [:slugged, :finders]

   def slug_candidates
      [ :name, [:id, :name] ]
   end

   def should_generate_new_friendly_id?
      name_changed? || super
   end

end

app/models/artist.rb
class Artist < ActiveRecord::Base

   extend FriendlyId

   include SearchCop

   acts_as_votable

   has_many :albums

   has_attached_file :avatar, styles: {
      medium: '200x200',
      thumb: '100x100'
   }

   validates_attachment_content_type :avatar, content_type: /\Aimage/
   validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/, /gif\Z/]
   validates_with AttachmentSizeValidator,
      attributes: :avatar,
      less_than: 5.megabytes
   do_not_validate_attachment_file_type :avatar

   search_scope :search do
      attributes :name, :slug
   end

   friendly_id :slug_candidates, use: [:slugged, :finders]

   def slug_candidates
      [ :name, [:id, :name] ]
   end

   def should_generate_new_friendly_id?
      name_changed? || super
   end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
   belongs_to :user
   has_many :tracks
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/selection.rb
class Selection < ActiveRecord::Base

   has_many :tracks

   has_attached_file :avatar, styles: { medium: '300x300', thumb: '150x150' }

   validates_attachment_content_type :avatar, content_type: /\Aimage/
   validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/, /gif\Z/]
   validates_with AttachmentSizeValidator,
      attributes: :avatar,
      less_than: 5.megabytes
   do_not_validate_attachment_file_type :avatar

end

app/models/style.rb
class Style < ActiveRecord::Base
   has_many :albums

   has_attached_file :avatar, styles: { medium: '300x300', thumb: '150x150' }

   validates_attachment_content_type :avatar, content_type: /\Aimage/
   validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/, /gif\Z/]
   validates_with AttachmentSizeValidator,
      attributes: :avatar,
      less_than: 5.megabytes
   do_not_validate_attachment_file_type :avatar
end

app/models/track.rb
class Track < ActiveRecord::Base

   extend FriendlyId

   belongs_to :album
   belongs_to :playlist
   belongs_to :selection

   has_attached_file :track_file

   validates_attachment_content_type :track_file, :content_type => [ 'audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio' ]
   #validates_with AttachmentSizeValidator,
   #attributes: :track_file,
   #less_than: 5.megabytes
   do_not_validate_attachment_file_type :track_file

   friendly_id :slug_candidates, use: [:slugged, :finders]

   def slug_candidates
      [ :name, [:id, :name] ]
   end

   def should_generate_new_friendly_id?
      name_changed? || super
   end

end

app/models/user.rb
class User < ActiveRecord::Base

   acts_as_voter

   has_many :playlists
   has_many :favorites
   has_many :favorite_artists, through: :favorites, source: :favorited, source_type: 'Artist'
   has_many :favorite_albums, through: :favorites, source: :favorited, source_type: 'Album'
   has_many :favorite_selections, through: :selections, source: :favorited, source_type: 'Selection'

   rolify
   devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   def index
      if user_signed_in?
         redirect_to root_path
      else
         redirect_to new_user_session_path
      end
   end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
   before_action :authenticate_user!
   before_action :display_playlists

   def index
      @fav_artists = current_user.favorite_artists.order(:created_at).limit(6)
      @fav_albums = current_user.favorite_albums.order(:created_at).limit(6)
      @user_playlists = Playlist.limit(6)
   end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
   def gravatar_url(user)
      gravatar_id = Digest::MD5::hexdigest(user.email).downcase
      "http://gravatar.com/avatar/#{gravatar_id}.png"
   end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/index/index.html.erb
<div id="favorites">
   <!-- Albums enregistrés -->
   <section id="favorite-artists">
      <h2 class="col-md-12">Mes albums</h2>
      <% @fav_albums.each do |favorite| %>
         <div class="favorite col-md-2">
            <%= link_to favorite.avatar.exists? ? image_tag(favorite.avatar.url(:medium)) : '&empty;'.html_safe, favorite %>
            <p class="artist-name"><%= link_to favorite.name, favorite %></p>
         </div>
      <% end %>
      <%= link_to 'Voir tous mes albums favoris', display_favorite_albums_path, class: 'link-to-favorites col-md-12' %>
   </section>

   <!-- Artistes favoris -->
   <section id="favorite-artists">
      <h2 class="col-md-12">Mes artistes</h2>
      <% @fav_artists.each do |favorite| %>
         <div class="favorite col-md-2">
            <%= link_to favorite.avatar.exists? ? image_tag(favorite.avatar.url(:medium)) : '&empty;'.html_safe, favorite %>
            <p class="artist-name"><%= link_to favorite.name, favorite %></p>
         </div>
      <% end %>
      <%= link_to 'Voir tous mes artistes favoris', display_favorite_artists_path, class: 'link-to-favorites col-md-12' %>
   </section>

   <!-- Playlists -->
   <section id="playlists">
      <h2 class="col-md-12">Mes playlists</h2>
      <% if @user_playlists %>
         <% @user_playlists.each do |playlist| %>
            <div class="favorite col-md-2">
               <div class="playlist-icon"><i class="fa fa-music" aria-hidden="true"></i></div>
               <p class="playlist-name"><%= link_to playlist.name, playlist %></p>
            </div>
         <% end %>
      <% end %>
   </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vyco</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="/public/favicon.png" />
  <%= csrf_meta_tags %>

  <!-- FONTS -->
  <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

</head>
<% if user_signed_in? %>
<body id="main-page">
<% else %>
<body id="login-page">
<% end %>

   <% if user_signed_in? %>
      <header id="main-header" class="container-fluid">
         <div class="row">
            <div class="col-md-9">
               <div class="col-md-2">
                  <%= link_to "Vyco", root_path, :class => "logo" %>
               </div>
               <div class="col-md-10">
                  <ul>
                     <% if can? :create, Artist %>
                        <li class="col-md-2"><%= link_to 'Ajouter un artiste', new_artist_path %></li>
                     <% end %>
                     <% if can? :create, Playlist %>
                        <li class="col-md-2"><%= link_to 'Ajouter une playlist', new_playlist_path %></li>
                     <% end %>
                     <% if can? :create, Track %>
                        <li class="col-md-2"><%= link_to 'Ajouter un track', new_track_path %></li>
                     <% end %>
                     <% if can? :create, Album %>
                        <li class="col-md-2"><%= link_to 'Ajouter un album', new_album_path %></li>
                     <% end %>
                     <% if can? :create, Style %>
                        <li class="col-md-2"><%= link_to 'Ajouter un style', new_style_path %></li>
                     <% end %>
                  </ul>
               </div>
            </div>
            <div id="user-informations" class="col-md-3"><span class="gravatar"><%= image_tag gravatar_url(current_user) %></span> Hello <%= current_user.email %> <%= link_to('Déconnexion', destroy_user_session_path, :method => :delete, :class => "logout") %>
         </div>
      </header>
   <% else %>
      <div id="login-header">
         <%= content_tag :span, "Vyco", :class => "logo" %>
      </div>
   <% end %>

   <div class="container-fluid wrapper">
      <div class="row">
         <% if user_signed_in? %>
         <div id="sidebar" class="col-md-3 col-sm-3 col-xs-5">

            <%= link_to "Vyco", root_path, :class => "logo" %>

            <div id="user-informations">
               <span class="gravatar"><%= image_tag gravatar_url(current_user) %></span>
               <p>Hello <%= current_user.email %></p>
               <%= link_to('Déconnexion', destroy_user_session_path, :method => :delete, :class => "logout") %>
            </div>

            <!-- Sidebar -->
            <div id="sidebar-nav">
               <section id="discover">
                  <h3>Parcourir</h3>
                  <p>Découvrir</p>
                  <p><%= link_to 'Artistes', artists_path %></p>
                  <p><%= link_to 'Albums', albums_path %></p>
               </section>

               <section id="music">
                  <h3>Ma musique</h3>
                  <p>Artistes</p>
                  <p>Albums</p>
               </section>

               <section id="playlists">
                  <h3>Mes playlists</h3>
                  <div id="new-playlist">
                     <i class="fa fa-plus-circle" aria-hidden="true"></i>
                     <%= link_to 'Nouvelle playlist', new_playlist_path %>
                  </div>
                  <% if @playlists %>
                     <% @playlists.each do |playlist| %>
                        <p><i class="fa fa-music" aria-hidden="true"></i> <%= link_to playlist.name, playlist %></p>
                     <% end %>
                  <% end %>
               </section>
            </div><!-- #sidebar-nav -->
         </div>
         <% end %>

         <% if user_signed_in? %>
            <div class="col-md-9 col-sm-9 col-xs-7 col-md-offset-3 col-sm-offset-3 col-xs-offset-5">
               <%= yield %>
            </div>
         <% else %>
            <div class="col-md-12 wrapper login-content">
               <%= yield %>
            </div>
         <% end %>
      </div>
   </div>

</body>
</html>