config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :artists
  resources :playlists
  resources :tracks
  resources :albums
  resources :styles
  resource :admins
  resource :selections
  resource :display_favorite_artists
  resource :display_favorite_albums
  resources :favorite_artists, only: [:create, :destroy]
  resources :favorite_albums, only: [:create, :destroy]
  root 'index#index'
  get 'index' => 'home#index'
  get 'favorite_artists' => 'display_favorite_artists#show'
  get 'favorite_albums' => 'display_favorite_albums#show'

  resources :artists do
     member do
        put "like" => "artists#upvote"
        put "dislike" => "artists#downvote"
     end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
     user ||= User.new

      if user.has_role?(:admin)
         can :manage, Artist
         can :manage, Playlist
         can :manage, Track
         can :manage, Album
         can :manage, Style
         can :manage, Selection
      else
         can :read, Artist
         can :read, Playlist
         can :read, Track
         can :read, Album
         can :read, Style
         can :read, Selection
      end
   end
end

app/models/album.rb
class Album < ActiveRecord::Base

   extend FriendlyId

   include SearchCop

   has_many :tracks
   belongs_to :style
   belongs_to :artist

   has_attached_file :avatar, styles: { medium: '300x300', thumb: '150x150' }

   validates_attachment_content_type :avatar, content_type: /\Aimage/
   validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/, /gif\Z/]
   validates_with AttachmentSizeValidator,
      attributes: :avatar,
      less_than: 5.megabytes
   do_not_validate_attachment_file_type :avatar

   search_scope :search do
      attributes :name, :slug
   end

   friendly_id :slug_candidates, use: [:slugged, :finders]

   def slug_candidates
      [ :name, [:id, :name] ]
   end

   def should_generate_new_friendly_id?
      name_changed? || super
   end

end

app/models/artist.rb
class Artist < ActiveRecord::Base

   extend FriendlyId

   include SearchCop

   acts_as_votable

   has_many :albums

   has_attached_file :avatar, styles: {
      medium: '200x200',
      thumb: '100x100'
   }

   validates_attachment_content_type :avatar, content_type: /\Aimage/
   validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/, /gif\Z/]
   validates_with AttachmentSizeValidator,
      attributes: :avatar,
      less_than: 5.megabytes
   do_not_validate_attachment_file_type :avatar

   search_scope :search do
      attributes :name, :slug
   end

   friendly_id :slug_candidates, use: [:slugged, :finders]

   def slug_candidates
      [ :name, [:id, :name] ]
   end

   def should_generate_new_friendly_id?
      name_changed? || super
   end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
   belongs_to :user
   has_many :tracks
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/selection.rb
class Selection < ActiveRecord::Base

   has_many :tracks

   has_attached_file :avatar, styles: { medium: '300x300', thumb: '150x150' }

   validates_attachment_content_type :avatar, content_type: /\Aimage/
   validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/, /gif\Z/]
   validates_with AttachmentSizeValidator,
      attributes: :avatar,
      less_than: 5.megabytes
   do_not_validate_attachment_file_type :avatar

end

app/models/style.rb
class Style < ActiveRecord::Base
   has_many :albums

   has_attached_file :avatar, styles: { medium: '300x300', thumb: '150x150' }

   validates_attachment_content_type :avatar, content_type: /\Aimage/
   validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/, /gif\Z/]
   validates_with AttachmentSizeValidator,
      attributes: :avatar,
      less_than: 5.megabytes
   do_not_validate_attachment_file_type :avatar
end

app/models/track.rb
class Track < ActiveRecord::Base

   extend FriendlyId

   belongs_to :album
   belongs_to :playlist
   belongs_to :selection

   has_attached_file :track_file

   validates_attachment_content_type :track_file, :content_type => [ 'audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio' ]
   #validates_with AttachmentSizeValidator,
   #attributes: :track_file,
   #less_than: 5.megabytes
   do_not_validate_attachment_file_type :track_file

   friendly_id :slug_candidates, use: [:slugged, :finders]

   def slug_candidates
      [ :name, [:id, :name] ]
   end

   def should_generate_new_friendly_id?
      name_changed? || super
   end

end

app/models/user.rb
class User < ActiveRecord::Base

   acts_as_voter

   has_many :playlists
   has_many :favorites
   has_many :favorite_artists, through: :favorites, source: :favorited, source_type: 'Artist'
   has_many :favorite_albums, through: :favorites, source: :favorited, source_type: 'Album'
   has_many :favorite_selections, through: :selections, source: :favorited, source_type: 'Selection'

   rolify
   devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

   def index
   end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   def index
      if user_signed_in?
         redirect_to root_path
      else
         redirect_to new_user_session_path
      end
   end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
   before_action :authenticate_user!
   before_action :display_playlists

   def index
      @fav_artists = current_user.favorite_artists.order(:created_at).limit(6)
      @fav_albums = current_user.favorite_albums.order(:created_at).limit(6)
      @user_playlists = Playlist.limit(6)
   end

end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
   authorize_resource
   before_action :authenticate_user!
   before_action :set_style, only: [:show, :edit, :update, :destroy]
   before_action :display_playlists

   def index
      @styles = Style.all
   end

   def show
   end

   def new
      @style = Style.new
   end

   def edit
   end

   def create
      @style = Style.new(style_params)

      if @style.save
         redirect_to @style, notice: 'The musical style was successfully created.'
      else
         render :new
      end
   end

   def update
       if @style.update(style_params)
          redirect_to @style, notice: 'The musical style was successfully updated.'
       else
          render :edit
       end
   end

   def destroy
     @style.destroy
     redirect_to styles_url, notice: 'The musical style was successfully destroyed.'
   end

   private
     def set_style
       @style = Style.find(params[:id])
     end

     def style_params
       params.require(:style).permit(:name, :avatar)
     end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
   def gravatar_url(user)
      gravatar_id = Digest::MD5::hexdigest(user.email).downcase
      "http://gravatar.com/avatar/#{gravatar_id}.png"
   end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/selections_helper.rb
module SelectionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/styles/_form.html.erb
<%= simple_form_for(@style) do |f| %>
  <% if @style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
      <% @style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
     <div class="add-field col-md-5">
        <%= f.input :name, label: 'Nom du style musical' %>
     </div>
  </div>

  <div class="row">
     <div class="col-md-5">
       <%= f.input :avatar, as: :file, class: 'style-avatar', label: 'Image' %>
     </div>
  </div>

  <div class="actions">
    <%= f.submit 'Enregistrer', class: 'btn-submit' %>
  </div>
<% end %>

app/views/styles/_style.html.erb
<% if style.present? %>
   <%= style_link(style) %>
<% else %>
   &empty;
<% end %>

app/views/styles/edit.html.erb
<div class="back-button col-md-2">
   <i class="fa fa-arrow-left" aria-hidden="true"></i>
   <%= link_to 'Retour', artists_path %>
</div>

<div class="update-section col-md-10 col-md-offset-1">
   <h1>Modifier un style musical</h1>
   <%= render 'form' %>
</div>

app/views/styles/index.html.erb
<% if can? :create, Style %>
   <div class="col-md-2">
      <%= link_to 'Nouveau style musical', new_style_path, class: 'add-new-style add' %>
   </div>
<% end %>

<div id="styles-list">
   <% @styles.each do |style| %>
      <div class="style col-md-3">
         <div class="style-avatar">
            <%= style.avatar.exists? ? image_tag(style.avatar.url(:medium)) : '&empty;'.html_safe %>
            <p class="style-name"><%= style.name %></p>
         </div>
         <% if can? :create, Style %>
            <div class="edit-section">
               <%= link_to 'Modifier', edit_style_path(style) %>
               <%= link_to 'Supprimer', style, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
         <% end %>
      </div>
   <% end %>
</div>

app/views/styles/new.html.erb
<div class="back-button col-md-2">
   <i class="fa fa-arrow-left" aria-hidden="true"></i>
   <%= link_to 'Retour', styles_path %>
</div>

<div class="add-section col-md-10 col-md-offset-1">
   <h1>Ajouter un style musical</h1>
   <%= render 'form' %>
</div>

app/views/styles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @style.name %>
</p>

<%= link_to 'Edit', edit_style_path(@style) %> |
<%= link_to 'Back', styles_path %>