config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :artists
  resources :playlists
  resources :tracks
  resources :albums
  resources :styles
  resource :admins
  resource :selections
  resource :display_favorite_artists
  resource :display_favorite_albums
  resources :favorite_artists, only: [:create, :destroy]
  resources :favorite_albums, only: [:create, :destroy]
  root 'index#index'
  get 'index' => 'home#index'
  get 'favorite_artists' => 'display_favorite_artists#show'
  get 'favorite_albums' => 'display_favorite_albums#show'

  resources :artists do
     member do
        put "like" => "artists#upvote"
        put "dislike" => "artists#downvote"
     end
  end

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
   belongs_to :user
   has_many :tracks
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
   authorize_resource
   before_action :authenticate_user!
   before_action :set_playlist, only: [:show, :edit, :update, :destroy]
   before_action :display_playlists

   def index
      @playlists = Playlist.all
   end

   def show
   end

   def new
      @playlist = Playlist.new
   end

   def edit
   end

   def create
      playlist_params[:user_id] = current_user.id
      @playlist = Playlist.new(playlist_params)

      if @playlist.save
         redirect_to root_path, notice: 'Playlist was successfully created.'
      else
         render :new
      end
   end

   def update
      if @playlist.update(playlist_params)
         redirect_to @playlist, notice: 'Playlist was successfully updated.'
      else
         render :edit
      end
   end

   def destroy
      @playlist.destroy
      redirect_to playlists_url, notice: 'Playlist was successfully destroyed.'
   end

   private
      def set_playlist
         @playlist = Playlist.find(params[:id])
      end

      def playlist_params
         params.require(:playlist).permit(:name, :user_id)
      end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= simple_form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
     <div class="add-field col-md-5">
        <%= f.input :name, label: 'Nom de la playlist' %>
     </div>
  </div>

  <div class="actions">
    <%= f.submit 'Enregistrer', class: 'btn-submit' %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<div class="back-button col-md-2">
   <i class="fa fa-arrow-left" aria-hidden="true"></i>
   <%= link_to 'Retour', artists_path %>
</div>

<div class="update-section col-md-10 col-md-offset-1">
   <h1>Modifier une playlist</h1>
   <%= render 'form' %>
</div>

app/views/playlists/index.html.erb
<h1>Listing Playlists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Id user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.name %></td>
        <td><%= playlist.id_user %></td>
        <td><%= link_to 'Show', playlist %></td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
        <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playlist', new_playlist_path %>

app/views/playlists/new.html.erb
<div class="back-button col-md-2">
   <i class="fa fa-arrow-left" aria-hidden="true"></i>
   <%= link_to 'Retour', playlists_path %>
</div>

<div class="add-section col-md-10 col-md-offset-1">
   <h1>Ajouter une playlist</h1>
   <%= render 'form' %>
</div>

app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @playlist.name %>
</p>

<p>
  <strong>Id user:</strong>
  <%= @playlist.id_user %>
</p>

<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>